# Generated by Django 4.0.3 on 2022-03-11 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grupo', '0001_initial'),
        ('setor', '0001_initial'),
        ('turno', '0001_initial'),
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='grupo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='grupo.grupo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='setor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='setor.setor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='turno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='turno.turno'),
            preserve_default=False,
        ),
    ]
