# Generated by Django 4.0.3 on 2022-03-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0001_initial'),
        ('funcionarios', '0002_funcionario_grupo_funcionario_setor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='skill',
            field=models.ManyToManyField(to='skill.skill'),
        ),
    ]
