# Generated by Django 4.0.3 on 2022-03-11 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unidade', '0001_initial'),
        ('funcionarios', '0003_funcionario_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='unidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='unidade.unidade'),
            preserve_default=False,
        ),
    ]
